---

language: python
os: linux
dist: focal
services: docker

env:
  global:
    - ROLE_NAME: awscli2
  jobs:
    - MOLECULE_DISTRO: centos:8
    - MOLECULE_DISTRO: centos:7

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME deekayen.$ROLE_NAME
  - cd deekayen.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
