---

language: python
dist: bionic
services: docker

env:
  global:
    - ROLE_NAME: molecule_sandbox
  matrix:
    - MOLECULE_DISTRO: ubuntu:bionic
    - MOLECULE_DISTRO: ubuntu:xenial
    - MOLECULE_DISTRO: ubuntu:trusty
    - MOLECULE_DISTRO: debian:10
    - MOLECULE_DISTRO: debian:9
    - MOLECULE_DISTRO: debian:8

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME deekayen.$ROLE_NAME
  - cd deekayen.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
