---

language: python
dist: bionic
services: docker

env:
  global:
    - ROLE_NAME: awscli2
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7

before_install:
  # Upgrade Docker to work with docker-py.
  - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash

install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME deekayen.$ROLE_NAME
  - cd deekayen.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
