---

language: python
os: linux
dist: bionic
services: docker

env:
  global:
    - ROLE_NAME: molecule_sandbox
  jobs:
    - MOLECULE_DISTRO: ubuntu:bionic
    - MOLECULE_DISTRO: ubuntu:xenial
    - MOLECULE_DISTRO: debian:10
    - MOLECULE_DISTRO: debian:9

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME deekayen.$ROLE_NAME
  - cd deekayen.$ROLE_NAME

script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
